/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./src/components/app/background.vue')['default']
    HomeHeader: typeof import('./src/components/home/header.vue')['default']
    HomeSeriesItem: typeof import('./src/components/home/series-item.vue')['default']
    IconDelete: typeof import('./src/components/icon/delete.vue')['default']
    IconDownload: typeof import('./src/components/icon/download.vue')['default']
    IconEpisodes: typeof import('./src/components/icon/episodes.vue')['default']
    IconExternal: typeof import('./src/components/icon/external.vue')['default']
    IconHome: typeof import('./src/components/icon/home.vue')['default']
    IconLink: typeof import('./src/components/icon/link.vue')['default']
    IconNext: typeof import('./src/components/icon/next.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesEpisodeItem: typeof import('./src/components/series/episode-item.vue')['default']
    SeriesHeader: typeof import('./src/components/series/header.vue')['default']
  }
}
