/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundImage: typeof import('./src/components/background-image.vue')['default']
    EpisodeItem: typeof import('./src/components/episode-item.vue')['default']
    IconDelete: typeof import('./src/components/icon/delete.vue')['default']
    IconDownload: typeof import('./src/components/icon/download.vue')['default']
    IconEpisodes: typeof import('./src/components/icon/episodes.vue')['default']
    IconExternal: typeof import('./src/components/icon/external.vue')['default']
    IconHome: typeof import('./src/components/icon/home.vue')['default']
    IconLink: typeof import('./src/components/icon/link.vue')['default']
    IconNext: typeof import('./src/components/icon/next.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesHeader: typeof import('./src/components/series-header.vue')['default']
    SeriesItem: typeof import('./src/components/series-item.vue')['default']
  }
}
